### ISSUE TITLE
vcard 4.0 non-english language

### ISSUE THREAD

**Issue by Dutik** [2amigos/qrcode-library#27]
$format = new vCardFormat();

$format->lang = "ru-RU";
$format->name = "Antonio тест";
$qrCode = new QrCode($format);
header('Content-Type: ' . $qrCode->getContentType());
echo $qrCode->writeString();

return name «Antonio —Ç–µ—Å—Ç»

**Comment by Dutik** [comment]
Perhaps it's better to use 3rd version instead of the 4?

**Comment by tonydspaniard** [comment]
Unable to help with russian

**Comment by 2amjsouza** [comment]
The data is properly encoded in QRCode, the issue itself is related to supported alphabets on readers.

```php
$format = new VCardFormat();
$format->lang = "ru-RU";
$format->name = "Antonio тест тоныдспаниард Тест Стринг";

$text = new QrCode($format);
Storage::put('qrcode/test.png', $text->writeString());
```

![test](https://github.com/2amigos/qrcode-library/assets/142612126/031af8ea-32ab-483b-a003-0aa33c47d7fb)

e.g. **iOS built in qrcode reader:**

![image](https://github.com/2amigos/qrcode-library/assets/142612126/82cf1ce2-fcbd-4d81-9bce-48310a89876c)


using **QRbot app:**

![image](https://github.com/2amigos/qrcode-library/assets/142612126/53c8350c-e49c-4da4-8b4a-60a8ee6165c3)
