### ISSUE TITLE
Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by huaiguoguo** [2amigos/qrcode-library#30]
### What steps will reproduce the problem?
在使用组件：2amigos/yii2-qrcode-helper  的时候，报以下bug,  please !  thanks 
### What is the expected result?
在使用组件：2amigos/yii2-qrcode-helper  的时候，报以下bug,  please !  thanks 
### What do you get instead?
![image](https://user-images.githubusercontent.com/1888094/37964711-fced5e7e-31f4-11e8-9e82-645bc76b331e.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      |  7.2.3 nts 64bit
| Operating system | win10 64bit

**Comment by tonydspaniard** [comment]
Last version of the library fixed that. Maybe you could consider a change?

**Comment by vietnux** [comment]
me also problem on

**Comment by spider4216** [comment]
I faced with this problem too and send patch #37  to fix this problem

**Comment by tonydspaniard** [comment]
I'll try to make a version patch for this
