### ISSUE TITLE
How to generate file in SVG format?

### ISSUE THREAD

**Issue by cesarcgfg** [2amigos/qrcode-library#39]
Please, is it possible to generate file in SVG format?

Regards

**Comment by tonydspaniard** [comment]
Yes you can, you need to use a different writer https://github.com/2amigos/qrcode-library/blob/master/src/QrCode.php#L88 that uses https://github.com/Bacon/BaconQrCode/blob/master/src/Renderer/Image/SvgImageBackEnd.php

**Comment by tonydspaniard** [comment]
need to update the library thought to the latest :(

**Comment by cesarcgfg** [comment]
Hi,
Thank you so mucho for your help. It just worked really good. 

But I'm finding a new issue, when using the SVGWriter the Label is not printed.

`
$qrCode = (new \Da\QrCode\QrCode('https://example.com', null, new SvgWriter()))
            ->setSize(300)
            ->setLabel(new Label('QR Code Text', null,24));
return $qrCode->writeString();
`
The SVGWriter is not adding the Label.

Regards
