### ISSUE TITLE
SVGWriter does not add Label

### ISSUE THREAD

**Issue by cesarcgfg** [2amigos/qrcode-library#40]
Hi,
Thank you so much for your help. I implemented the SVGWriter as you suggested.

But I'm finding a new issue, when using the SVGWriter the Label is not printed.

```
$qrCode = (new \Da\QrCode\QrCode('https://example.com', null, new SvgWriter()))
            ->setSize(300)
            ->setLabel(new Label('QR Code Text', null,24));

return $qrCode->writeString();
```

Regards

_Originally posted by @cesarcgfg in https://github.com/2amigos/qrcode-library/issues/39#issuecomment-516564766_

**Comment by 2amjsouza** [comment]
fix applied and released on patch 3.0.1
