### ISSUE TITLE
I am facing error Class 'BaconQrCode\Renderer\Image\Png' not found

### ISSUE THREAD

**Issue by asifrafeeq** [2amigos/qrcode-library#41]
hi, thanks a lot for such a nice library, I am using qrcode-library which is working fine in localhost, but when I upload it to online hosting it gives the error of 
`Class 'BaconQrCode\Renderer\Image\Png' not found`

**My code is like this** 

```
$qrCode = (new QrCode($model->name))
                                ->setSize(250)
                                ->setMargin(5)
                                ->useForegroundColor(51, 153, 255);


                                echo '<img src="' . $qrCode->writeDataUri() . '">';
```

please guide me how can I solve my issue
![error](https://user-images.githubusercontent.com/2939341/63841113-3e0e2280-c993-11e9-99e6-829e4ce16180.jpg)

**Comment by tonydspaniard** [comment]
When you upload your code, do you also upload the vendor folder (composer?)

**Comment by asifrafeeq** [comment]
the yiisoft/extensions file was not updated, now it is working fine.
thank u so much for guidance.
