### ISSUE TITLE
Setter functions and clone

### ISSUE THREAD

**Issue by LorisZ** [2amigos/qrcode-library#42]
Hi,

I wanted to know if there is a reason every setter function clones the object instead of just setting the property? Just seems weird and confusing, not sure if there is actually a point in doing so?

Also some of the "setter" functions are called useSomething instead of setSomething, which also seems a bit weird.

**Comment by tonydspaniard** [comment]
you correct. this code is quite old, will update very soon. I wanted to keep immutability but i guess is silly.
