### ISSUE TITLE
Incorrect QR code generated

### ISSUE THREAD

**Issue by dayaram3388** [2amigos/qrcode-library#43]
To start with, thank you for providing open source libraries for individuals like us to quickly deliver the client tasks. I have a question pertaining to the QR codes generated using your library. Incidentally, few of the random QR codes are not readable. 

I checked the 4 elements to be present: - Position marking- Alignment marking- Timing Marking- Quiet zone 

It seems all are present, but still the reference attached QR code is not readable? Could you advise the problem in here! Incidentally, my client has printed more than 30K+ QR codes physically, and to control the situation, am trying to first understand the problem - and then find possible solution. 

For your reference, the data stored on this reference QR code image is CARD-7818-1407-1311-191015-184607

Any help would be appreciated. 
![CARD-7818-1407-1311-191015-184607](https://user-images.githubusercontent.com/32100633/68273349-2e464500-008c-11ea-94cb-a8fba263a14c.png)

**Comment by tonydspaniard** [comment]
sorry for the delay, i think the problem is the logo within.

**Comment by 2amjsouza** [comment]
Hi, the logo should be up to 16% the qrcode size, you have a little bit more in this sample

![image](https://github.com/2amigos/qrcode-library/assets/142612126/6b732f61-0022-4e43-ae54-5671da735893)

Here's a sample using the data you provided:

```php
$text = (new QrCode('CARD-7818-1407-1311-191015-184607'))
	->setSize(91)
	->setLogo(public_path('assets/logo.png'))
	->setLogoWidth(14);
	
Storage::put('qrcode/test.png', $text->writeString());
```
![test](https://github.com/2amigos/qrcode-library/assets/142612126/5fcdc4bc-f373-4fcd-a964-6173ec27120a)
