### ISSUE TITLE
when  can php 8.x be supported?

### ISSUE THREAD

**Issue by huaiguoguo** [2amigos/qrcode-library#47]
i am use php8 ,
it's had a error when composer require 2amigos/qrcode-library;
when  can php 8.x be supported?

i look require bacon/bacon-qr-code: ^1.0,   
bacon/bacon-qr-code   was updated  2.x

last time , i am thank you  good library

**Comment by sJonatas** [comment]
PHP8 is supported already. BaconQrCode ^2 will be supported on very next release
duplicated
#49

**Comment by sJonatas** [comment]
the release 3.0.0-beta supports BaconQrCode ^2
Update the dependency to use:

`composer require 2amigos/qrcode-library:3.0.0-beta`
