### ISSUE TITLE
Support for Bacon/BaconQrCode ^2.0 needed for PHP 8.1

### ISSUE THREAD

**Issue by rafaelmiti** [2amigos/qrcode-library#49]
That is some prevision to when support for "Bacon/BaconQrCode ^2.0" will be added? That's blocking our PHP 8.1 upgrade.

Check the following issue: https://github.com/Bacon/BaconQrCode/issues/110

**Comment by xinlongnews** [comment]
邮件已收到！

**Comment by monta990** [comment]
any update?

**Comment by xinlongnews** [comment]
邮件已收到！

**Comment by sJonatas** [comment]
BaconBarcode ^2 will be suported on the very next release

**Comment by sJonatas** [comment]
the release 3.0.0-beta supports BaconQrCode ^2
Update the dependency to use:

`composer require 2amigos/qrcode-library:3.0.0-beta`
