### ISSUE TITLE
QR codes not working in iOS 17.4

### ISSUE THREAD

**Issue by eguerin-ucsf** [2amigos/qrcode-library#70]
BookmarFormat doesn't make a readable QR code.

No usable data found, haven't found a work around.  Tried with and without a title. 

I found a similar issue on Apple website but restarting phone didn't fix the issue.  Some other Libs seem to work. 

Also tried the generator on this page
https://2am.tech/open-source/qrcode-generator/
and the same thing happened, so it's not my coding.

**Comment by xinlongnews** [comment]
邮件已收到！

**Comment by 2amjsouza** [comment]
Hello @eguerin-ucsf we really appreciate your report.
The Bookmark format follows [MEBKM bookmark format](https://web.archive.org/web/20160213153725/https://www.nttdocomo.co.jp/english/service/developer/make/content/barcode/function/application/bookmark/) and unfortunately is not been properly recognized on ios camera app, even been properly read by other readers.
If you're trying to assess a qrcode to build an url only, you can simply use the text format (default one) with your link with `https://` (or http://), by the way:

```php
<?php
$qrCode = (new QrCode('https://2am.tech/'));

echo '<img src="' . $qrCode->writeDataUri() . '">';
```

![image](https://github.com/2amigos/qrcode-library/assets/142612126/8bb6c909-6d08-48ac-9057-cd67a62d5e93)

**Comment by eguerin-ucsf** [comment]
Thanks, eventually i figured that out, took awhile though!
